# DS 3000/CS 3200 Lab 1

Due: Tuesday May 13 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

Use the markdown language below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a link to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.  Aim for roughly 3 sentences total of text.

# NATO
## The North Atlantic Treaty Organization
### READ ME: before Thursday, May 15, unless you wanna look like a loser when we visit NATO

NATO is an alliance of countries from Europe and North America. It provides a unique link between these two continents, enabling them to consult and cooperate in the field of defence and security, and conduct multinational crisis-management operations together.

![NATO Logo](https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Flag_of_NATO.svg/500px-Flag_of_NATO.svg.png)

| Country       | Capital        | NATO Member Since |
|---------------|----------------|-------------------|
| United States | Washington, DC | 1949 (for now)    |
| France        | Paris          | 1949              |
| Germany       | Berlin         | 1955              |
| Canada        | Ottawa         | 1949              |


- Collective defense principle
- Founded after World War II
- Includes the US, UK, France, Germany, etc

Learn more on the [official NATO website](https://www.nato.int).

The formula for your final grade is:

$$
\text{grade} = weight_1 \times score_1 + weight_2 \times score_2
$$


# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [2]:
# make sure to import numpy library
import numpy as np

In [3]:
#Creating/saving the arrays
array_a = np.array([[3, 8, -2, 3],
                    [0.5, -1, 6, 4],
                    [-5, 7, -42, 2]])

array_b = np.array([[42, 38, 34],
                    [30, 26, 22],
                    [18, 14, 10],
                    [6, 2, -2],
                    [-6, -10, -14]])

In [4]:
#Print array_a
print(array_a)

[[  3.    8.   -2.    3. ]
 [  0.5  -1.    6.    4. ]
 [ -5.    7.  -42.    2. ]]


In [5]:
#Print array_b
print(array_b)

[[ 42  38  34]
 [ 30  26  22]
 [ 18  14  10]
 [  6   2  -2]
 [ -6 -10 -14]]


## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [23]:
print("array_a shape:", array_a.shape)
print("array_a size:", array_a.size)
print("array_a ndim:", array_a.ndim)
print("array_a nbytes:", array_a.nbytes)

print("array_b shape:", array_b.shape)
print("array_b size:", array_b.size)
print("array_b ndim:", array_b.ndim)
print("array_b nbytes:", array_b.nbytes)


array_a shape: (3, 4)
array_a size: 12
array_a ndim: 2
array_a nbytes: 96
array_b shape: (5, 3)
array_b size: 15
array_b ndim: 2
array_b nbytes: 120


In [24]:
#2: transpose both arrays
t_array_a = array_a.T
t_array_b = array_b.T

In [25]:
# Trying to add array a and t_array_b which ValueError due to shape mismatch because t_array_b is (3, 5)
# print(array_a + t_array_b)

# Slice to match (3, 4)
t_array_b_trimmed = t_array_b[:, :-1]  

# Now adding together 
result = array_a + t_array_b_trimmed
print(result)

[[ 45.   38.   16.    9. ]
 [ 38.5  25.   20.    6. ]
 [ 29.   29.  -32.    0. ]]


When adding array_a and transposed array b, the dimensions of array a is (3,4) and transposed array b is (3,5). This would cause a ValueError because the numbers of rows are not equal. To solve this, I sliced to match the shape to (3, 4) which is why I "-1". from there I was able to add the results together. 

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [4]:
# make sure to import pandas library
import pandas as pd

df = pd.read_csv("train_stations_europe.csv", index_col="id")
df.head()

name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [5]:
#please don't bully me for using "not equal to true" instead of "equal to false". for some reason, equal to false didn't work
belgium_subset = df[(df["country"] == "BE") & (df["is_city"] != "TRUE")]
belgium_subset.head()
belgium_subset.describe()

# Ive included the right way you are supposed to do it to show you I know how
right_way_belgium_subset = df[(df["country"] == "BE") & (df["is_city"] == "FALSE")]
right_way_belgium_subset.describe()

latitude  longitude  parent_station_id
count       0.0        0.0                0.0
mean        NaN        NaN                NaN
std         NaN        NaN                NaN
min         NaN        NaN                NaN
25%         NaN        NaN                NaN
50%         NaN        NaN                NaN
75%         NaN        NaN                NaN
max         NaN        NaN                NaN

# Part 4: GitHub (10 points)

When you finish the first three parts, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer25), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer25 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.